spring.application.name=testAIRagVectorDB

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=codellama:latest

spring.data.mongodb.uri=mongodb+srv://bratabitan:root123@cluster0.uaqwttk.mongodb.net/
spring.data.mongodb.database=neelAiDB
spring.ai.ollama.embedding.options.model=nomic-embed-text:latest
spring.ai.ollama.embedding.model=nomic-embed-text

spring.ai.vectorstore.mongodb.initialize-schema=true
spring.ai.vectorstore.mongodb.collection-name=vector_store
spring.ai.vectorstore.mongodb.index-name=vector_index

